spring:
  datasource:
    url: jdbc:h2:mem:library
    #initialization-mode: never
    initialization-mode: always
    schema: schema.sql
    data: data.sql

  shell:
    interactive:
      enabled: false

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
    console.enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  main:
    allow-circular-references: true

    properties:
      hibernate:
        format_sql: true

    show-sql: true


logging:
  level:
    ROOT: ERROR