DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE GENRES(ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, NAME VARCHAR(255), CONSTRAINT GenreName UNIQUE (NAME));
CREATE TABLE AUTHORS(ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, NAME VARCHAR(255), CONSTRAINT AuthorName UNIQUE (NAME));
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT, TITLE VARCHAR(255), AUTHOR INT references AUTHORS(ID), GENRE INT references GENRES(ID), CONSTRAINT AuthorTitle UNIQUE (TITLE, AUTHOR));

