DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE GENRES(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255),
    CONSTRAINT GenreName UNIQUE (NAME)
);
CREATE TABLE AUTHORS(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255),
    CONSTRAINT AuthorName UNIQUE (NAME)
);
CREATE TABLE BOOKS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255),
    AUTHOR INT references AUTHORS(ID) on delete cascade,
    GENRE INT references GENRES(ID),
    CONSTRAINT AuthorTitle UNIQUE (TITLE, AUTHOR)
);
CREATE TABLE COMMENTS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BOOK BIGINT references BOOKS(ID) on delete cascade,
    TEXT VARCHAR(4096),
    datetime TIMESTAMP NOT NULL
);
